networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false
  proxy:
    name: proxy
services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=yde001@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      #- "traefik.log.level=DEBUG"
    networks:
      - app
      - frontend

  phpfpm:
    image: itkdev/php8.4-fpm:alpine
    user: ${COMPOSE_USER:-deploy}
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
    #    depends_on:
    #     mariadb:
    #       condition: service_healthy
    volumes:
      - .:/app

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    restart: unless-stopped
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
      - mercure
    volumes:
      - ./.docker/templates:/etc/nginx/templates:ro
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
    environment:
      NGINX_FPM_SERVICE: ${COMPOSE_PROJECT_NAME}-phpfpm-1:9000
      NGINX_WEB_ROOT: /app/public
      NGINX_PORT: 8080
      NGINX_MAX_BODY_SIZE: 5M
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver"

  mail:
    image: axllent/mailpit
    networks:
      - app
      - frontend
    ports:
      - "1025"
      - "8025"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}mail.rule=Host(`mail-${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}mail.loadbalancer.server.port=8025"

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    networks:
      - app
      - frontend
    environment:
      # Uncomment the following line to disable HTTPS,
      #SERVER_NAME: ':80'
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_JWT_SECRET}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_JWT_SECRET}"
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://knaekker.dk
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    #healthcheck:
    #  test: ["CMD", "curl", "-I", "https://mercure-scavenger.local.itkdev.dk/healthz"]
    #  timeout: 5s
    #  retries: 5
    #  start_period: 60s
    ports:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}mercure.rule=Host(`mercure-${COMPOSE_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}mercure.middlewares=redirect-to-https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}mercure.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  ###< symfony/mercure-bundle ###

  node:
    image: node:20
    profiles:
      # Used only to build assets
      - dev
    working_dir: /app
    volumes:
      - .:/app

  rabbit:
    image: rabbitmq:4-management-alpine
    networks:
      - app
      - frontend
    ports:
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  supervisor:
    image: itkdev/supervisor-php8.4:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 scheduler_default
      - APP_SUPERVISOR_WORKERS=1
      - APP_SUPERVISOR_USER=deploy
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app

volumes:
  mercure_data:
  mercure_config:
