parameters:
    admin_api_url: '%env(ADMIN_API_URL)%'
    admin_api_key: '%env(ADMIN_API_KEY)%'
    mercure_public_url: '%env(MERCURE_PUBLIC_URL)%'
    mercure_jwt_secret: '%env(MERCURE_JWT_SECRET)%'
    app.race_theme_default: '%env(RACE_THEME_DEFAULT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $raceThemeDefault: '%app.race_theme_default%'
            $defaultTheme: '%app.race_theme_default%'

    App\:
        resource: "../src/"

    Scavenger\Shared\ApiClient\AdminApiClient:
        arguments:
            $adminApiUrl: '%admin_api_url%'
            $apiKey: '%admin_api_key%'

    App\Twig\MercureExtension:
        arguments:
            $mercureJwtSecret: '%mercure_jwt_secret%'
            $mercurePublicUrl: '%mercure_public_url%'

    App\Twig\RaceThemeExtension:
        arguments:
            $defaultTheme: '%app.race_theme_default%'
