webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    strict_mode: true

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
