parameters:
    admin_api_url: '%env(ADMIN_API_URL)%'
    admin_api_key: '%env(ADMIN_API_KEY)%'
    race_frontend_url: 'https://race-%env(COMPOSE_DOMAIN)%'
    admin_url: 'https://admin-%env(COMPOSE_DOMAIN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"

    Scavenger\Shared\ApiClient\AdminApiClient:
        arguments:
            $adminApiUrl: '%admin_api_url%'
            $apiKey: '%admin_api_key%'
